# using 2.1 since depends_on not available on v3
version: '2.1'

services:
  rabbit:
    image: 'rabbitmq:3.7.1'
    ports:
      - 9000:5672
    volumes:
      - ./services/rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit
    healthcheck:
      test: exit 0
      interval: 10s
      timeout: 10s
      retries: 3

  logger:
    build: ./services/logger
    environment:
      rabbitConnectionString: "amqp://rabbit"
      DEBUG: "*"
    links:
      - rabbit
    depends_on:
      rabbit:
        condition: service_healthy

  indexer:
    build: ./services/index-service
    environment:
      rabbitConnectionString: "amqp://rabbit"
      DEBUG: "*"
    links:
      - rabbit
      - logger
    depends_on:
      rabbit:
        condition: service_healthy

  dasher:
    build: ./services/dasher
    environment:
      rabbitConnectionString: "amqp://rabbit"
      tmpDir: "/tmpDir"
      outDir: "/outDir"
      DEBUG: "*"
      workerCount: 4
    volumes:
      - ./shared-volumes/dash-output:/outDir
    links:
      - rabbit
      - logger
    depends_on:
      rabbit:
        condition: service_healthy

